version: '3.7'

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2020-07-02T00-15-09Z
    command: server /data
    restart: always
    volumes:
    - /data:/data
    - ./volumes/staging:/tmp/staging
    ports:
    - "9000:9000"
    env_file:
    - ./minio-variables.env    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  proxy:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/nginx-conf:/etc/nginx/conf.d
      - ./volumes/nginx-certs:/etc/nginx/certs
      - ./volumes/nginx-vhost:/etc/nginx/vhost.d
      - ./volumes/nginx-html:/usr/share/nginx/html

  proxy-generator:
    container_name: nginx-proxy-gen
    restart: always
    image: jwilder/docker-gen
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/nginx-conf:/etc/nginx/conf.d
      - ./volumes/nginx-certs:/etc/nginx/certs
      - ./volumes/nginx-vhost:/etc/nginx/vhost.d
      - ./volumes/nginx-html:/usr/share/nginx/html
      - ./templates:/etc/docker-gen/templates
    command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

  certificates:
    container_name: nginx-letsencrypt
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - proxy
      - proxy-generator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/nginx-certs:/etc/nginx/certs
      - ./volumes/nginx-vhost:/etc/nginx/vhost.d
      - ./volumes/nginx-html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
    env_file:
      - letsencrypt-variables.env

